# Generated by Django 4.0.4 on 2022-08-21 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_id_english_level_alter_cardpost_id_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpost',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='like',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id_english_level',
        ),
        migrations.AddField(
            model_name='cardpost',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_category', to='api.category'),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_user', to='api.user'),
        ),
        migrations.AddField(
            model_name='like',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_card', to='api.cardpost'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='api.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='english_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_english_level', to='api.englishlevel'),
        ),
    ]
