# Generated by Django 4.0.4 on 2022-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='pedromorales@gmail.com', max_length=254),
        ),
    ]
