# Generated by Django 4.0.2 on 2022-07-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategory', models.IntegerField()),
                ('name', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('firstLastName', models.CharField(max_length=50)),
                ('secondLastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('english_level', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idMessage', models.IntegerField()),
                ('message', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.user')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLike', models.IntegerField()),
                ('score', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.user')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCard', models.IntegerField()),
                ('content', models.CharField(max_length=1000)),
                ('translation', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('idCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.category')),
                ('idUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.user')),
            ],
        ),
    ]
