# Generated by Django 4.0.2 on 2022-08-26 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='idCard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionUsuarios.card'),
        ),
        migrations.AlterField(
            model_name='like',
            name='score',
            field=models.FloatField(),
        ),
    ]
