# Generated by Django 4.0.2 on 2022-03-31 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='idCard',
        ),
        migrations.RemoveField(
            model_name='like',
            name='idLike',
        ),
        migrations.RemoveField(
            model_name='message',
            name='idMessage',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idUser',
        ),
    ]
