# Generated by Django 4.0.2 on 2022-03-31 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionUsuarios', '0002_remove_card_idcard_remove_like_idlike_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='updated_at',
        ),
    ]
